### ISSUE TITLE
ios10 cannot use Json

### ISSUE THREAD

**Issue by Wenbile** [carson-katri/swift-request#29]
Compiling for iOS 10.0, but module 'Json' has a minimum deployment target of iOS 13.0

**Comment by carson-katri** [comment]
This is due to a dependence on Combine for the Request library. I believe that you must set the minimum target for all libraries in the package, so there isn’t a way for the Json library to have a lower target.

There are other Json libraries such as SwiftyJSON which work quite well and you may consider instead.

Hope it works out and eventually you can target iOS 13 as the minimum 😀
